### ISSUE TITLE
Publish on F-droid

### ISSUE THREAD

**Issue by opk12** [Akaflieg-Freiburg/addhoursandminutes#12]
[F-droid](https://f-droid.org/) is a repository of free (libre) Android apps, independent of Google Play. It is the de-facto standard in the free-software Android community. It is analogous to the Debian `main` repository, but for Android.

Having the app in F-droid would widen the audience, help people de-google a bit, and shorten the gap between Android and mobile GNU/Linux, for the already de-googled.

The base requirement is that the source code and libraries are under a free license, as detailed in the [Inclusion Policy](https://f-droid.org/en/docs/Inclusion_Policy/). The build server has Debian stable (customizable in the build recipe) with upstream Android SDK. The app can be built reproducibly, if you want so; this is actually encouraged. Check out [the docs](https://f-droid.org/en/docs/) for more info.

**Comment by kebekus** [comment]
@opk12 Thank you for the suggestion.

I fully endorse publishing my apps on F-Droid, but I do not have the manpower to do that myself. So, I am looking for a volunteer who ports the apps to the F-Droid build system and maintains them in the future. Regretfully, our last attempts have failed. After initial enthusiasm, the app version on F-Droid started to lag behind and was eventually not maintained anymore. Regretfully, we were forced to withdraw the app from F-Droid.

If you are willing to invest the necessary time and do all the work, then please be in touch! I close this issue now, but I will read your comments.

**Comment by opk12** [comment]
That's clear, thank you for the quick reply. I don't have the time to maintain a public build recipe, but I can ask other people. Do you have any pointers to prior work (I could not find the recipe in fdroiddata's git history) and do you have similar apps in the same situation?

**Comment by kebekus** [comment]
@opk12 Thanks for the prompt reply. The app "Add Times" is only a sidekick to "Enroute Flight Navigation," a navigation app for pilots that was available on F-Droid for a while. I did not upload the app to F-Droid myself, but I think one pointer to fdroiddata is here:

- https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7880

Best,

Stefan.

**Comment by opk12** [comment]
So it's Enroute's issue 252, yet another case of the Qt SDK being a known blocker for apps to enter F-droid. This is ultimately not an issue of maintainance - downloading prebuilt binaries is a security issue for the end user, prevents reproducible builds, and technically makes the app non-libre. I see a use case for this app outside flying, but we can only wait if F-droid ever adds a Debian `contrib` equivalent (unlikely, due to the security issue) or, hopefully, an update from Qt.

**Comment by kebekus** [comment]
@opk12 Correct. We do build Qt from sources for other platforms, but the build is so complicated that the F-Droid maintainer gave up. I am sorry that we have no better news.
